# Generated by Django 3.0.1 on 2020-01-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(help_text='Enter your book name', max_length=15)),
                ('author_name', models.CharField(blank=True, help_text='Enter your author name', max_length=15)),
                ('total_pieces', models.IntegerField(help_text='Enter your total pieces')),
                ('price', models.IntegerField(help_text='Enter the price')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Enter your number', max_length=10)),
                ('book_name', models.CharField(default='author', help_text='Enter your book name', max_length=1000)),
                ('total', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=15)),
                ('second_name', models.CharField(blank=True, help_text='Enter your second name', max_length=15)),
                ('number', models.CharField(help_text='Enter your phone number', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
